package action

import (
	"bytes"
	"encoding/json"
	"fmt"
	"math/big"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var typescriptIdentifier = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// GenerateTypeScriptCatalog derives channel-facing TypeScript contracts from
// the same schemas registered by the Action Runtime. Exact numeric literals
// outside JavaScript's safe integer range are rejected rather than rounded.
func GenerateTypeScriptCatalog(descriptors []Descriptor) ([]byte, error) {
	items := make([]Descriptor, 0, len(descriptors))
	for index, descriptor := range descriptors {
		prepared, err := PrepareDescriptor(descriptor)
		if err != nil {
			return nil, fmt.Errorf("prepare Action descriptor at index %d: %w", index, err)
		}
		items = append(items, prepared.Descriptor())
	}
	sort.Slice(items, func(i, j int) bool { return items[i].ID < items[j].ID })
	for index := 1; index < len(items); index++ {
		if items[index-1].ID == items[index].ID {
			return nil, fmt.Errorf("Action descriptor id %q is declared more than once", items[index].ID)
		}
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by modary action catalog; DO NOT EDIT.\n\n")
	if err := writeTypeScriptFrameworkErrors(&output); err != nil {
		return nil, err
	}
	output.WriteString("export interface ActionContracts {\n")
	for _, descriptor := range items {
		input, err := schemaTypeScript(descriptor.InputSchema)
		if err != nil {
			return nil, fmt.Errorf("action %s input schema: %w", descriptor.ID, err)
		}
		result, err := schemaTypeScript(descriptor.OutputSchema)
		if err != nil {
			return nil, fmt.Errorf("action %s output schema: %w", descriptor.ID, err)
		}
		actionID, err := typescriptStringLiteral(descriptor.ID)
		if err != nil {
			return nil, fmt.Errorf("action %s id: %w", descriptor.ID, err)
		}
		fmt.Fprintf(&output, "  %s: {\n    input: %s;\n", actionID, input)
		if len(descriptor.PreviewSchema) > 0 {
			preview, err := schemaTypeScript(descriptor.PreviewSchema)
			if err != nil {
				return nil, fmt.Errorf("action %s preview schema: %w", descriptor.ID, err)
			}
			fmt.Fprintf(&output, "    preview: %s;\n", preview)
		}
		fmt.Fprintf(&output, "    output: %s;\n", result)
		if len(descriptor.Errors) > 0 {
			output.WriteString("    errors: {\n")
			for _, spec := range descriptor.Errors {
				code, err := typescriptStringLiteral(spec.Code)
				if err != nil {
					return nil, fmt.Errorf("action %s error code %q: %w", descriptor.ID, spec.Code, err)
				}
				kind, err := typescriptStringLiteral(string(spec.Kind))
				if err != nil {
					return nil, fmt.Errorf("action %s error code %q kind: %w", descriptor.ID, spec.Code, err)
				}
				fmt.Fprintf(&output, "      %s: %s;\n", code, kind)
			}
			output.WriteString("    };\n")
		}
		output.WriteString("  };\n")
	}
	output.WriteString("}\n\n")
	output.WriteString("export type ActionID = keyof ActionContracts;\n")
	output.WriteString("export type PreviewActionID = { [ID in ActionID]: ActionContracts[ID] extends { preview: unknown } ? ID : never }[ActionID];\n")
	output.WriteString("export type ActionInput<ID extends ActionID> = ActionContracts[ID][\"input\"];\n")
	output.WriteString("export type ActionOutput<ID extends ActionID> = ActionContracts[ID][\"output\"];\n")
	output.WriteString("export type ActionPreview<ID extends ActionID> = ActionContracts[ID] extends { preview: infer Preview } ? Preview : never;\n")
	output.WriteString("export type FrameworkActionErrorCode = Extract<keyof FrameworkActionErrors, string>;\n")
	output.WriteString("export type DeclaredActionErrorCode<ID extends ActionID> = ActionContracts[ID] extends { errors: infer Errors } ? Extract<keyof Errors, string> : never;\n")
	output.WriteString("export type ActionErrorCode<ID extends ActionID> = FrameworkActionErrorCode | DeclaredActionErrorCode<ID>;\n")
	output.WriteString("export type ActionErrorKind<ID extends ActionID, Code extends ActionErrorCode<ID>> = Code extends FrameworkActionErrorCode ? FrameworkActionErrors[Code] : ActionContracts[ID] extends { errors: infer Errors } ? Code extends keyof Errors ? Errors[Code] : never : never;\n")
	return output.Bytes(), nil
}

func writeTypeScriptFrameworkErrors(output *bytes.Buffer) error {
	specs := make([]ErrorSpec, 0, len(builtinErrorKinds))
	for code, kind := range builtinErrorKinds {
		specs = append(specs, ErrorSpec{Code: code, Kind: kind})
	}
	sort.Slice(specs, func(i, j int) bool { return specs[i].Code < specs[j].Code })

	output.WriteString("export interface FrameworkActionErrors {\n")
	for _, spec := range specs {
		code, err := typescriptStringLiteral(spec.Code)
		if err != nil {
			return fmt.Errorf("framework Action error code %q: %w", spec.Code, err)
		}
		kind, err := typescriptStringLiteral(string(spec.Kind))
		if err != nil {
			return fmt.Errorf("framework Action error code %q kind: %w", spec.Code, err)
		}
		fmt.Fprintf(output, "  %s: %s;\n", code, kind)
	}
	output.WriteString("}\n\n")
	return nil
}

func schemaTypeScript(schema json.RawMessage) (string, error) {
	node, err := decodeSingleJSON(schema)
	if err != nil {
		return "", err
	}
	return schemaNodeTypeScript(node)
}

func schemaNodeTypeScript(value any) (string, error) {
	node, ok := value.(map[string]any)
	if !ok {
		return "unknown", nil
	}
	if constant, exists := node["const"]; exists {
		return typescriptLiteral(constant)
	}
	if choices, exists := node["enum"].([]any); exists {
		parts := make([]string, 0, len(choices))
		for _, choice := range choices {
			literal, err := typescriptLiteral(choice)
			if err != nil {
				return "", err
			}
			parts = append(parts, literal)
		}
		return strings.Join(parts, " | "), nil
	}
	if choices, exists := node["oneOf"].([]any); exists {
		parts := make([]string, 0, len(choices))
		for _, choice := range choices {
			converted, err := schemaNodeTypeScript(choice)
			if err != nil {
				return "", err
			}
			parts = append(parts, converted)
		}
		return strings.Join(parts, " | "), nil
	}
	switch node["type"] {
	case "string":
		return "string", nil
	case "integer", "number":
		return "number", nil
	case "boolean":
		return "boolean", nil
	case "array":
		item, err := schemaNodeTypeScript(node["items"])
		if err != nil {
			return "", err
		}
		if strings.Contains(item, " | ") {
			item = "(" + item + ")"
		}
		return "Array<" + item + ">", nil
	case "object":
		properties, _ := node["properties"].(map[string]any)
		patternProperties, _ := node["patternProperties"].(map[string]any)
		if len(properties) == 0 {
			if len(patternProperties) > 0 {
				return "Record<string, unknown>", nil
			}
			switch additional := node["additionalProperties"].(type) {
			case bool:
				if additional {
					return "Record<string, unknown>", nil
				}
				return "Record<string, never>", nil
			case map[string]any:
				converted, err := schemaNodeTypeScript(additional)
				if err != nil {
					return "", err
				}
				return "Record<string, " + converted + ">", nil
			default:
				return "Record<string, unknown>", nil
			}
		}
		required := make(map[string]struct{})
		if items, ok := node["required"].([]any); ok {
			for _, item := range items {
				if name, ok := item.(string); ok {
					required[name] = struct{}{}
				}
			}
		}
		names := make([]string, 0, len(properties))
		for name := range properties {
			names = append(names, name)
		}
		sort.Strings(names)
		parts := make([]string, 0, len(names)+1)
		for _, name := range names {
			converted, err := schemaNodeTypeScript(properties[name])
			if err != nil {
				return "", err
			}
			propertyName := name
			if !typescriptIdentifier.MatchString(name) {
				propertyName, err = typescriptStringLiteral(name)
				if err != nil {
					return "", fmt.Errorf("encode property name %q: %w", name, err)
				}
			}
			optional := "?"
			if _, exists := required[name]; exists {
				optional = ""
			}
			parts = append(parts, propertyName+optional+": "+converted)
		}
		// TypeScript cannot express JSON Schema's "all keys except known or
		// regex-matched keys" rule. An unknown index signature retains the
		// useful types of named properties without rejecting valid dynamic keys.
		if len(patternProperties) > 0 || objectAllowsAdditionalProperties(node) {
			parts = append(parts, "[key: string]: unknown")
		}
		return "{ " + strings.Join(parts, "; ") + " }", nil
	default:
		return "unknown", nil
	}
}

func objectAllowsAdditionalProperties(node map[string]any) bool {
	additional, exists := node["additionalProperties"]
	if !exists {
		return true
	}
	closed, isBoolean := additional.(bool)
	return !isBoolean || closed
}

func typescriptLiteral(value any) (string, error) {
	switch typed := value.(type) {
	case string:
		return typescriptStringLiteral(typed)
	case nil:
		return "null", nil
	case json.Number:
		return typescriptNumberLiteral(typed)
	default:
		if err := validateTypeScriptNumbers(typed); err != nil {
			return "", err
		}
		canonical, err := canonicalizeJSONValue(typed)
		if err != nil {
			return "", err
		}
		data, err := json.Marshal(canonical)
		if err != nil {
			return "", err
		}
		return string(data), nil
	}
}

func typescriptStringLiteral(value string) (string, error) {
	encoded, err := json.Marshal(value)
	if err != nil {
		return "", fmt.Errorf("encode TypeScript string literal: %w", err)
	}
	return string(encoded), nil
}

func validateTypeScriptNumbers(value any) error {
	return validateTypeScriptNumbersAt(value, "$")
}

func validateTypeScriptNumbersAt(value any, location string) error {
	switch typed := value.(type) {
	case json.Number:
		_, err := typescriptNumberLiteral(typed)
		if err != nil {
			return fmt.Errorf("%s: %w", location, err)
		}
	case map[string]any:
		keys := make([]string, 0, len(typed))
		for key := range typed {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			if err := validateTypeScriptNumbersAt(typed[key], jsonPointer(location, key)); err != nil {
				return err
			}
		}
	case []any:
		for index, item := range typed {
			if err := validateTypeScriptNumbersAt(item, fmt.Sprintf("%s/%d", location, index)); err != nil {
				return err
			}
		}
	}
	return nil
}

func jsonPointer(base, component string) string {
	component = strings.ReplaceAll(component, "~", "~0")
	component = strings.ReplaceAll(component, "/", "~1")
	return base + "/" + component
}

func typescriptNumberLiteral(value json.Number) (string, error) {
	normalized, err := normalizeJSONNumber(value.String())
	if err != nil {
		return "", err
	}
	rational, ok := new(big.Rat).SetString(normalized)
	if !ok {
		return "", fmt.Errorf("JSON number %q is invalid", value)
	}
	maximumSafeInteger := new(big.Rat).SetInt64(9_007_199_254_740_991)
	if new(big.Rat).Abs(rational).Cmp(maximumSafeInteger) > 0 {
		return "", fmt.Errorf("JSON numeric literal %q is outside JavaScript's safe integer range", value)
	}
	parsed, err := strconv.ParseFloat(normalized, 64)
	if err != nil {
		return "", fmt.Errorf("JSON numeric literal %q is not a finite JavaScript number", value)
	}
	roundTrip := strconv.FormatFloat(parsed, 'g', -1, 64)
	roundTripRational, ok := new(big.Rat).SetString(roundTrip)
	if !ok || roundTripRational.Cmp(rational) != 0 {
		return "", fmt.Errorf("JSON numeric literal %q cannot be represented exactly by a JavaScript number literal", value)
	}
	return normalized, nil
}
