package module

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type Project struct {
	Root      string
	App       AppManifest
	Manifests []Manifest
	Graph     Graph
}

func LoadProject(root string) (Project, error) {
	app, err := LoadAppManifest(filepath.Join(root, "modary.yaml"))
	if err != nil {
		return Project{}, err
	}
	seen := make(map[string]struct{}, len(app.Modules))
	manifests := make([]Manifest, 0, len(app.Modules))
	for _, id := range app.Modules {
		if _, exists := seen[id]; exists {
			return Project{}, fmt.Errorf("module %s appears more than once in modary.yaml", id)
		}
		seen[id] = struct{}{}
		manifest, err := LoadManifest(filepath.Join(root, "modules", id, "module.yaml"))
		if err != nil {
			return Project{}, err
		}
		if manifest.ID != id {
			return Project{}, fmt.Errorf("module directory %s contains manifest for %s", id, manifest.ID)
		}
		manifests = append(manifests, manifest)
	}
	graph, err := Verify(manifests)
	if err != nil {
		return Project{}, err
	}
	if err := VerifySourceBoundaries(root); err != nil {
		return Project{}, err
	}
	return Project{Root: root, App: app, Manifests: manifests, Graph: graph}, nil
}

func VerifySourceBoundaries(root string) error {
	return filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			if entry.Name() == "node_modules" || entry.Name() == ".git" || entry.Name() == "dist" {
				return filepath.SkipDir
			}
			return nil
		}
		if filepath.Ext(path) != ".go" || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		parsed, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ImportsOnly)
		if err != nil {
			return fmt.Errorf("parse imports in %s: %w", relative, err)
		}
		for _, imported := range parsed.Imports {
			value, err := strconv.Unquote(imported.Path.Value)
			if err != nil {
				return err
			}
			if strings.HasPrefix(relative, "core"+string(filepath.Separator)) && strings.HasPrefix(value, "modary/modules/") {
				return fmt.Errorf("module boundary violation: %s imports %s", relative, value)
			}
			if strings.HasPrefix(relative, "modules"+string(filepath.Separator)) && strings.Contains(value, "/internal/") && strings.HasPrefix(value, "modary/modules/") {
				parts := strings.Split(filepath.ToSlash(relative), "/")
				if len(parts) > 1 && !strings.HasPrefix(value, "modary/modules/"+parts[1]+"/internal/") {
					return fmt.Errorf("module boundary violation: %s imports %s", relative, value)
				}
			}
		}
		return nil
	})
}

func (project Project) Generate() error {
	if err := project.generateGoRegistry(); err != nil {
		return err
	}
	if err := project.generateUIRegistry(); err != nil {
		return err
	}
	if err := writeJSON(filepath.Join(project.Root, "internal", "generated", "module_graph.json"), project.Graph); err != nil {
		return err
	}
	type actionRecord struct {
		ID     string `json:"id"`
		Module string `json:"module"`
	}
	actions := make([]actionRecord, 0)
	for _, manifest := range project.Manifests {
		for _, id := range manifest.Actions {
			actions = append(actions, actionRecord{ID: id, Module: manifest.ID})
		}
	}
	sort.Slice(actions, func(i, j int) bool { return actions[i].ID < actions[j].ID })
	return writeJSON(filepath.Join(project.Root, "internal", "generated", "action_catalog.json"), actions)
}

func (project Project) generateGoRegistry() error {
	var source bytes.Buffer
	source.WriteString("// Code generated by modary generate; DO NOT EDIT.\n\n")
	source.WriteString("package generated\n\n")
	source.WriteString("import (\n\t\"modary/core/module\"\n")
	for _, id := range project.App.Modules {
		fmt.Fprintf(&source, "\t%s \"modary/modules/%s\"\n", goAlias(id), id)
	}
	source.WriteString(")\n\n")
	source.WriteString("func RegisterModules(host *module.Host) error {\n\treturn host.Register(\n")
	for _, id := range project.App.Modules {
		fmt.Fprintf(&source, "\t\t%s.Module(),\n", goAlias(id))
	}
	source.WriteString("\t)\n}\n")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return fmt.Errorf("format generated registry: %w", err)
	}
	return writeIfChanged(filepath.Join(project.Root, "internal", "generated", "modules_gen.go"), formatted)
}

func (project Project) generateUIRegistry() error {
	type route struct {
		ID     string
		Path   string
		Module string
		Entry  string
	}
	routes := make([]route, 0)
	for _, manifest := range project.Manifests {
		for _, item := range manifest.UI.Routes {
			routes = append(routes, route{ID: item.ID, Path: item.Path, Module: manifest.ID, Entry: item.Entry})
		}
	}
	sort.Slice(routes, func(i, j int) bool { return routes[i].ID < routes[j].ID })
	var generated bytes.Buffer
	generated.WriteString("// Code generated by modary generate; DO NOT EDIT.\n")
	generated.WriteString("import type { ModuleRoute } from \"../moduleTypes\";\n")
	entryAliases := make(map[string]string)
	aliasOwners := make(map[string]string)
	for _, item := range routes {
		key := item.Module + "\x00" + item.Entry
		if _, exists := entryAliases[key]; exists {
			continue
		}
		baseAlias := goAlias(item.Module) + "Routes"
		alias := baseAlias
		for suffix := 2; ; suffix++ {
			owner, collision := aliasOwners[alias]
			if !collision || owner == key {
				break
			}
			alias = fmt.Sprintf("%s%d", baseAlias, suffix)
		}
		entryAliases[key] = alias
		aliasOwners[alias] = key
		entry := strings.TrimPrefix(filepath.ToSlash(item.Entry), "./")
		entry = strings.TrimSuffix(strings.TrimSuffix(entry, ".tsx"), ".ts")
		fmt.Fprintf(&generated, "import { routes as %s } from %q;\n", alias, "../../../modules/"+item.Module+"/"+entry)
	}
	generated.WriteString("export const moduleRoutes = [\n")
	for _, item := range routes {
		alias := entryAliases[item.Module+"\x00"+item.Entry]
		fmt.Fprintf(&generated, "  %s[%q],\n", alias, item.ID)
	}
	generated.WriteString("] as const satisfies readonly ModuleRoute[];\n")
	if err := writeIfChanged(filepath.Join(project.Root, "web", "src", "generated", "routes.ts"), generated.Bytes()); err != nil {
		return err
	}
	var navigation bytes.Buffer
	navigation.WriteString("// Code generated by modary generate; DO NOT EDIT.\n")
	navigation.WriteString("import { moduleRoutes } from \"./routes\";\n\n")
	navigation.WriteString("export const moduleNavigation = moduleRoutes.filter((route) => route.navigation !== undefined);\n")
	return writeIfChanged(filepath.Join(project.Root, "web", "src", "generated", "navigation.ts"), navigation.Bytes())
}

func goAlias(id string) string {
	return strings.ReplaceAll(id, "-", "_")
}

func writeJSON(path string, value any) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	return writeIfChanged(path, append(data, '\n'))
}

func writeIfChanged(path string, data []byte) error {
	current, err := os.ReadFile(path)
	if err == nil && bytes.Equal(current, data) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
