CREATE TABLE modary_action_plan (
    plan_hash TEXT PRIMARY KEY,
    action_id TEXT NOT NULL,
    action_version TEXT NOT NULL,
    contract_hash TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    actor_type TEXT NOT NULL,
    channel TEXT NOT NULL,
    scope_kind TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    input_hash TEXT NOT NULL,
    payload_json BLOB NOT NULL,
    impact_rows INTEGER NOT NULL,
    impact_resources_json TEXT NOT NULL,
    snapshot_hash TEXT NOT NULL,
    decision_fingerprint TEXT NOT NULL,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    expires_at_unix_nano INTEGER NOT NULL,
    CHECK (length(plan_hash) = 71),
    CHECK (length(action_id) BETWEEN 1 AND 127),
    CHECK (length(action_version) BETWEEN 1 AND 128),
    CHECK (length(contract_hash) = 71),
    CHECK (length(actor_id) BETWEEN 1 AND 256),
    CHECK (length(actor_type) BETWEEN 1 AND 64),
    CHECK (length(channel) BETWEEN 1 AND 64),
    CHECK (length(scope_kind) BETWEEN 1 AND 64),
    CHECK (length(scope_id) BETWEEN 1 AND 256),
    CHECK (length(input_hash) = 71),
    CHECK (json_valid(payload_json)),
    CHECK (length(CAST(payload_json AS BLOB)) <= 1048576),
    CHECK (impact_rows >= 0),
    CHECK (json_valid(impact_resources_json)),
    CHECK (json_type(impact_resources_json) IN ('array', 'null')),
    CHECK (length(CAST(impact_resources_json AS BLOB)) <= 1048576),
    CHECK (COALESCE(json_array_length(impact_resources_json), 0) <= 32),
    CHECK (length(snapshot_hash) IN (0, 71)),
    CHECK (length(decision_fingerprint) BETWEEN 1 AND 256),
    CHECK (length(created_at) BETWEEN 20 AND 30),
    CHECK (length(expires_at) BETWEEN 20 AND 30)
) STRICT;

CREATE INDEX modary_action_plan_expiry_idx
    ON modary_action_plan (expires_at_unix_nano);

CREATE TABLE modary_action_idempotency (
    scope_kind TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    actor_type TEXT NOT NULL,
    action_id TEXT NOT NULL,
    action_version TEXT NOT NULL,
    contract_hash TEXT NOT NULL,
    channel TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    input_hash TEXT NOT NULL,
    plan_hash TEXT NOT NULL,
    impact_rows INTEGER NOT NULL,
    impact_resources_json TEXT NOT NULL,
    decision_fingerprint TEXT NOT NULL,
    status TEXT NOT NULL,
    result_data_json BLOB,
    result_summary TEXT NOT NULL,
    result_references_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (scope_kind, scope_id, actor_id, actor_type, action_id, idempotency_key),
    CHECK (length(scope_kind) BETWEEN 1 AND 64),
    CHECK (length(scope_id) BETWEEN 1 AND 256),
    CHECK (length(actor_id) BETWEEN 1 AND 256),
    CHECK (length(actor_type) BETWEEN 1 AND 64),
    CHECK (length(action_id) BETWEEN 1 AND 127),
    CHECK (length(action_version) BETWEEN 1 AND 128),
    CHECK (length(contract_hash) = 71),
    CHECK (length(channel) BETWEEN 1 AND 64),
    CHECK (length(idempotency_key) BETWEEN 1 AND 256),
    CHECK (length(input_hash) = 71),
    CHECK (length(plan_hash) = 71),
    CHECK (impact_rows >= 0),
    CHECK (json_valid(impact_resources_json)),
    CHECK (json_type(impact_resources_json) IN ('array', 'null')),
    CHECK (length(CAST(impact_resources_json AS BLOB)) <= 1048576),
    CHECK (COALESCE(json_array_length(impact_resources_json), 0) <= 32),
    CHECK (length(decision_fingerprint) BETWEEN 1 AND 256),
    CHECK (status IN ('running', 'completed')),
    CHECK (result_data_json IS NULL OR json_valid(result_data_json)),
    CHECK (result_data_json IS NULL OR length(CAST(result_data_json AS BLOB)) <= 1048576),
    CHECK (json_valid(result_references_json)),
    CHECK (json_type(result_references_json) IN ('array', 'null')),
    CHECK (length(CAST(result_references_json AS BLOB)) <= 1048576),
    CHECK (COALESCE(json_array_length(result_references_json), 0) <= 32),
    CHECK (length(result_summary) <= 512),
    CHECK (length(created_at) BETWEEN 20 AND 30),
    CHECK (length(updated_at) BETWEEN 20 AND 30),
    CHECK ((status = 'running' AND result_data_json IS NULL) OR
           (status = 'completed' AND result_data_json IS NOT NULL))
) STRICT;
